name: HoneyServer
main: Honey\Main
version: 1.1.0
api:
  - 3.0.0
  - 3.0.0-ALPHA11
load: STARTUP
author: towa0131
authors: [towa0131]
description: HoneyServer System Plugin
website: https://honey-mc.net
commands:
 loadreceipes:
  description: "レシピを再ロードします"
  usage: "/loadrecipes"
 reconnect:
  description: "サーバーへ再接続します"
  usage: "/reconnect"
  aliases: [rc]
 box:
  description: "アイテムボックスを開きます(ロビーでのみ使えます)"
  usage: "/box"
 status:
  description: "ユーザーのステータスを確認します"
  usage: "/status <name>"
  aliases: [stat]
 report:
  description: "違反ユーザーを報告します"
  usage: "/report"
  aliases: [rp]
 guild:
  description: "ギルド関係のコマンドです"
  usage: "/guild [join|quit|create|invite|deny|destroy]"
 entry:
  description: "ゲームへ参加します"
  usage: "/entry"
  aliases: [join]
permissions:
 admin.command:
  default: op